### PR TITLE
Add interactive to other mz layer

### PR DESCRIPTION
**Pull request by tallytalwar**
Refer https://github.com/tangrams/bubble-wrap/pull/249 for details.

### CODE REVIEW

**Comment by nvkelso** [comment]
@tallytalwar It looks like this was _attempted_ before on https://github.com/tangrams/cinnabar-style/blob/7291ff94653d9d80d59226ba81d35b00398b66d3/cinnabar-style.yaml#L845, but that's the wrong syntax for default `draw:` properties inside a style (introduced in TangramJS `v0.12.0`). Those interactive should also be removed.

**Review by nvkelso — CHANGES_REQUESTED** [review]
See https://github.com/tangrams/cinnabar-style/pull/27#issuecomment-303187956.

**Comment by tallytalwar** [comment]
Ohh I am not adding default style properties here. I am explicitly adding `interactive` to specific draw groups in a layer. `interactive` is a draw rule parameter: https://mapzen.com/documentation/tangram/draw/#interactive

**Comment by tallytalwar** [comment]
Will remove the ones we have in the styles though.

**Review by nvkelso — APPROVED** [review]

**Pull request merged**
